### ISSUE TITLE
[Feature Request] Ability to remove lights

### ISSUE THREAD

**Issue by dcosson** [chrisbsmith/homebridge-abode-lights#136]
I have an outlet plug that was powering Christmas lights, and now that I took the Christmas lights down and removed the device from Abode it still shows up in Homekit. I have restarted Homebridge, and each time I restart now the logs show the error "[Abode Lights] updateStatus did not find device ZW:00000013" but the Christmas lights are still showing up in Homekit.

It would be great if the device would automatically get removed from Homekit when this happens.

**Comment by chrisbsmith** [comment]
Nice catch. Totally agree. I'll look into this.

**Comment by chrisbsmith** [comment]
@dcosson , so I'm going to keep looking at the code to figure out a longer term solution, but have you tried restarting your homebridge? Devices are initially loaded at start where devices not found in the cache should be removed from homebridge.

**Comment by dcosson** [comment]
Yeah I've restarted homebridge several times (from the power button in the web UI). There is also a log message when starting up "Loading accessory from cache: Christmas Lights" and then the warning message that it could not find device. So maybe a caching issue? I am still seeing the old Christmas Lights device showing up in Homekit.

**Comment by chrisbsmith** [comment]
Thanks for the extra info. I do think it's a caching issue but the code should be able to handle this. I think I see where to make an update. Now to test, and to remember how to remove/add a device to Abode 😄

**Comment by chrisbsmith** [comment]
Hi @dcosson. I'm still looking into this but haven't found a very graceful way to remove the accessory just yet. Seems there's definitely a combination of removing it from cache and restarting homebridge. However, I did stumble upon this issue when investigating removing accessories from the cache: https://github.com/oznu/homebridge-config-ui-x/issues/525

It looks like the UI has changed a bit since and you can now remove single accessories rather than the entire cache. Can you give this a shot to remove the Christmas lights? I'm going to continue to look into a more graceful solution but hoping this works for now.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/602099/153761477-785044e7-c925-4716-9d2a-ffb2b632fd70.png">

**Comment by chrisbsmith** [comment]
@dcosson if you're still using this plugin, I've finally gotten around to adding this feature. `v2.0.0` introduces a few new things including this. Removing devices doesn't happen instantly, like adding devices. Instead I have to query Abode every few minutes, as defined by the `config.pollingInterval` setting. 

If you're still using the plugin, let me know if you run into any issues after upgrading.

Closing to #267
